### ISSUE TITLE
does not work with xfce4.12

### ISSUE THREAD

**Issue by produnis** [nandhp/multiload-nandhp#6]
does not work with xfce4.12.
It crashes on startup

**Comment by npoggi** [comment]
You need to recompile it, just did it after the upgrade to XFCE 4.12 and working fine :)

**Comment by produnis** [comment]
I could not compile it after that update. It crashed during compile because of package "lxpanel". I needed to de-install lxpanel, and after that, I could compile... Works now...

**Comment by nandhp** [comment]
lxpanel 0.7 introduces a backwards-incompatible API change; the multiload-nandhp lxpanel plugin will need to be rewritten to support newer versions of lxpanel. I've disabled building of the lxpanel plugin by default for the time being.
